config/routes.rb
Rails.application.routes.draw do
  get '/cart/add/:product_id', to: 'cart#add', as: 'add_to_cart'
  get '/cart/remove/:product_id', to: 'cart#remove', as: 'remove_from_cart'
  put '/cart/update/:product_id', to: 'cart#update', as: 'update_cart_item'
  get '/cart', to: 'cart#show', as: 'cart'

  resources :orders
  resources :products

  root "products#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :product_orders, dependent: :destroy
  has_many :products, through: :product_orders

  validates :first_name, :last_name, :address, :phone, presence: true

  def product_quantity(product)
    product_orders.find_by(product:).amount
  end

  def subtotal(product)
    product_orders.joins(:product)
                .where(product_orders: { product_id: product.id })
                .select('product_orders.amount * products.price AS subtotal')
                .first&.subtotal

  end

  def total_amount
    product_orders.joins(:product).sum('product_orders.amount * products.price')
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_orders, dependent: :destroy
  has_many :orders, through: :product_orders

  validates :name, presence: true
  validates :price, :balance, numericality: { greater_than_or_equal_to: 0 }
end

app/models/product_order.rb
class ProductOrder < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :amount, numericality: { greater_than: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cart_controller.rb
class CartController < ApplicationController

  def add
    product = Product.find(params[:product_id])
    cart_service.add_product(product.id)

    redirect_to root_path, notice: 'Product added to cart.'
  end

  def remove
    product_id = params[:product_id]
    cart_service.remove_product(product_id)

    redirect_to cart_path, notice: 'Product removed from cart.'
  end

  def update
    product_id = params[:product_id]
    quantity = params[:quantity]
    cart_service.update_product_quantity(product_id, quantity)

    redirect_to cart_path, notice: 'Cart updated.'
  end

  def show
    @cart_items = cart_service.cart_items
    @total_amount = cart_service.total_amount
  end

  private

  def cart_service
    @cart_service ||= CartService.new(session)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @orders = collection
  end

  def show
    @order = resource
  end

  def new
    @order = Order.new
    @cart_items = cart_service.cart_items
    @total_amount = cart_service.total_amount
  end

  def edit
    @order = resource
  end

  def create
    @order = OrderCreationService.new(order_params, cart, session).create_order

    if @order.persisted?
      redirect_to order_path(@order), notice: "Order was successfully created."
    else
      render :new
    end
  end

  def update
    @order = resource

    if @order.update(order_params)
      redirect_to @order, notice: 'Order was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @order = resource
    @order.destroy

    redirect_to orders_url, notice: 'Order was successfully destroyed.'
  end

  private

    def collection
      Order.all
    end

    def resource
      collection.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:first_name, :last_name, :address, :phone)
    end

    def cart
      session[:cart] ||= {}
    end

    def cart_service
      CartService.new(session)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = collection
  end

  def show
    @product = resource
  end

  def new
    @product = Product.new
  end

  def edit
    @product = resource
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product, notice: "Product was successfully created."
    else
      render :new
    end
  end

  def update
    @product = resource

    if @product.update(product_params)
      redirect_to @product, notice: "Product was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @product = resource
    @product.destroy
    redirect_to products_url, notice: "Product was successfully destroyed."
  end

  private

    def collection
      Product.all
    end

    def resource
      collection.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :description, :price, :balance)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cart/show.html.erb
<div class="w-full mx-auto md:w-1/2">
  <table id="cart" class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
    <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
      <tr>
        <th scope="col" class="px-6 py-3">#</th>
        <th scope="col" class="px-6 py-3">Product</th>
        <th scope="col" class="px-6 py-3">Price</th>
        <th scope="col" class="px-6 py-3">Quantity</th>
        <th scope="col" class="px-6 py-3">Subtotal</th>
      </tr>
    </thead>
    <tbody>
      <% @cart_items.each.with_index(1) do |cart_item, index| %>
        <tr>
          <th class="px-6 py-4 font-medium whitespace-nowrap"><%= index %></th>
          <td class="px-6 py-4 font-semibold text-gray-900 dark:text-white">
            <%= cart_item[:product].name %>
          </td>
          <td class="px-6 py-4 font-semibold text-gray-900 dark:text-white">
            <%= cart_item[:price] %>
          </td>
          <td class="px-6 py-4">
            <%= form_tag update_cart_item_path(product_id: cart_item[:product].id), method: :put, class: 'flex items-center' do %>
              <%= number_field_tag 'quantity', cart_item[:quantity], min: 1, class: 'w-16 mr-2 py-1 px-2 border rounded' %>
              <%= submit_tag 'Update', class: 'bg-gray-500 text-white py-1 px-3 rounded hover:bg-gray-600' %>
              <%= link_to 'Remove', remove_from_cart_path(product_id: cart_item[:product].id), method: :delete, class: 'text-red-500 hover:text-red-600 ml-2' %>
            <% end %>
          </td >
          <td class="px-6 py-4 font-semibold text-gray-900 dark:text-white">
            <%= cart_item[:subtotal] %>
          </td>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
      <tr class="border-b bg-neutral-100 dark:border-neutral-500 dark:bg-neutral-700">
        <th colspan="4" class="px-6 py-4 text-center whitespace-nowrap">Total:</th>
        <td class="px-6 py-4 font-semibold text-gray-900 dark:text-white"><%= @total_amount %></td>
      </tr>
    </tfoot>
  </table>
<!-- Make order button -->
  <%= button_to 'Make Order', new_order_path, method: :get, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium", style: "float: right"%>
</div>

app/views/layouts/_footer.html.erb
<footer class="text-center bg-neutral-200 dark:bg-neutral-700">
  <div class="p-4 text-center text-neutral-700 dark:text-neutral-200">
    <span class="text-center"> © <%= Date.current.year %> </span>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="relative flex flex-no-wrap items-center justify-between w-full py-2 shadow-md bg-neutral-100 shadow-black/5 dark:bg-neutral-600 dark:shadow-black/10 lg:flex-wrap lg:justify-start lg:py-4" data-te-navbar-ref>
  <div class="flex flex-wrap items-center justify-between w-full px-3">
    <div class="flex items-center justify-between" id="links">
      <%= link_to 'Products', products_path, class: "nav-item" %>
    </div>
    <div class="flex items-center justify-between" id="links">
      <%= link_to 'Cart', cart_path, class: "nav-item" %>
    </div>
</nav>

app/views/layouts/_notice.html.erb
  <% if notice.present? %>
    <p class="inline-block px-3 py-2 mb-5 font-medium text-green-500 rounded-lg bg-green-50" id="notice"><%= notice %></p>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eshop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="flex flex-col min-h-screen">
    <%= render "layouts/header" %>
    <%= render "layouts/notice" %>

    <main class="container flex-grow px-5 mx-auto mt-28">
      <%= yield %>
    </main>

    <%= render "layouts/footer" %>
  </body>
</html>

app/views/orders/_form.html.erb
<%= simple_form_for order do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :address %>
  <%= f.input :phone %>
  <%= f.button :submit %>
<% end %>

app/views/orders/_order.html.erb
<div id="<%= dom_id order %>">
  <p class="my-5">
    <strong class="block mb-1 font-medium">Firstname:</strong>
    <%= order.first_name %>
  </p>

  <p class="my-5">
    <strong class="block mb-1 font-medium">Lastname:</strong>
    <%= order.last_name %>
  </p>

  <p class="my-5">
    <strong class="block mb-1 font-medium">Address:</strong>
    <%= order.address %>
  </p>

  <p class="my-5">
    <strong class="block mb-1 font-medium">Phone:</strong>
    <%= order.phone %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this order", order, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this order', edit_order_path(order), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/orders/edit.html.erb
<h1>Edit Order</h1>

<%= render "orders/form", order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/new.html.erb
<div class="w-full mx-auto md:w-1/2">
  <h1 class="text-4xl font-bold text-center">New Order</h1>
  <br>
  <table id = "cart" class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
    <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
      <tr>
        <th scope="col" class="px-6 py-3">#</th>
        <th scope="col" class="px-6 py-3">Product</th>
        <th scope="col" class="px-6 py-3">Price</th>
        <th scope="col" class="px-6 py-3">Quantity</th>
        <th scope="col" class="px-6 py-3">Subtotal</th>
      </tr>
    </thead>
    <tbody>
      <% @cart_items.each.with_index(1) do |cart_item, index| %>
        <tr>
          <th class="px-6 py-4 font-medium whitespace-nowrap"><%= index %></th>
          <td class="px-6 py-4 font-semibold text-gray-900 dark:text-white">
            <%= cart_item[:product].name %>
          </td>
          <td class="px-6 py-4 font-semibold text-gray-900 dark:text-white">
            <%= cart_item[:price] %>
          </td>
          <td class="px-6 py-4 font-semibold text-gray-900 dark:text-white">
            <%= cart_item[:quantity] %>
          </td>
          <td class="px-6 py-4 font-semibold text-gray-900 dark:text-white">
            <%= cart_item[:subtotal] %>
          </td>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
      <tr class="border-b bg-neutral-100 dark:border-neutral-500 dark:bg-neutral-700">
        <th colspan="4" class="px-6 py-4 text-center whitespace-nowrap">Total:</th>
        <td class="px-6 py-4 font-semibold text-gray-900 dark:text-white"><%= @total_amount %></td>
      </tr>
    </tfoot>
  </table>
</div>
<br>
<br>
<br>
<div class="w-full mx-auto md:w-1/3">

  <%= render "orders/form", order: @order %>

  <%= link_to 'Back to cart', cart_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/orders/show.html.erb
<div class="w-full mx-auto md:w-1/2">

  <h1 class="mb-4 text-2xl font-bold text-center">Order Details</h1>
  <br>
  <div class="mb-4">
    <table id = "order" class="w-full text-sm text-left text-black-500 dark:text-gray-400">
      <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
        <tr>
          <th scope="col" class="px-6 py-3">Product</th>
          <th scope="col" class="px-6 py-3">Price</th>
          <th scope="col" class="px-6 py-3">Quantity</th>
          <th scope="col" class="px-6 py-3">Subtotal</th>
        </tr>
      </thead>
      <tbody>
        <% @order.products.each do |product| %>
          <tr>
            <td class="px-6 py-4 font-semibold text-gray-900 dark:text-white"><%= product.name %></td>
            <td class="px-6 py-4 font-semibold text-gray-900 dark:text-white"><%= product.price %></td>
            <td class="px-6 py-4 font-semibold text-gray-900 dark:text-white"><%= @order.product_quantity(product) %></td>
            <td class="px-6 py-4 font-semibold text-gray-900 dark:text-white"><%= @order.subtotal(product) %></td>
          </tr>
          <%  %>
        <% end %>
      </tbody>
      <tfoot>
        <tr class="border-b bg-neutral-100 dark:border-neutral-500 dark:bg-neutral-700">
          <th class="px-6 py-4 text-center whitespace-nowrap" colspan="3">Total Amount:</th>
          <td class="px-6 py-4 font-semibold text-gray-900 dark:text-white"><%= @order.total_amount %></td>
        </tr>
      </tfoot>
    </table>
  </div>
  <br>
  <br>
  <br>
  <div class="mb-4">
    <h2 class="text-xl font-bold">Order Information:</h2>
  </div>

  <div class="mb-4">
    <ul>
      <li><strong>Order Number:</strong> <%= @order.id %></li>
      <li><strong>First Name:</strong> <%= @order.first_name %></li>
      <li><strong>Last Name:</strong> <%= @order.last_name %></li>
      <li><strong>Address:</strong> <%= @order.address %></li>
      <li><strong>Phone:</strong> <%= @order.phone %></li>
    </ul>
  </div>

</div>

app/views/products/_form.html.erb
<%= simple_form_for product do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :balance %>
    <%= f.button :submit, input_html: { class: "bg-blue-500" } %>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>" class="p-5 border border-gray-200 rounded-lg">

  <h2 class="mb-2 text-lg font-semibold"><%= product.name %></h2>
  <div class="relative w-full mb-3 h-62 lg:mb-0">
      <img src="https://cdn.pixabay.com/photo/2017/01/11/11/33/cake-1971552__480.jpg" alt="Just a flower"
        class="object-fill w-full h-full rounded">
  </div>

  <p class="my-5">
    <strong class="block mb-1 font-medium">Description:</strong>
    <%= product.description %>
  </p>

  <p class="my-5">
    <strong class="block mb-1 font-medium">Price:</strong>
    <%= product.price %>
  </p>

  <p class="my-5">
    <strong class="block mb-1 font-medium">Balance:</strong>
    <%= product.balance %>
  </p>

  <div class="flex justify-between">
    <%= link_to "Show", product, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Add to Cart', add_to_cart_path(product_id: product.id), method: :post, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"%>
  </div>
</div>

app/views/products/edit.html.erb
<div class="w-full mx-auto md:w-1/3">
  <h1 class="text-4xl font-bold">Editing product</h1>

  <%= render "products/form", product: @product %>

  <%= link_to "Show this product", @product, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to products", products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/products/index.html.erb
<div class="w-full">
  <div class="flex items-center justify-between mb-5">
    <h1 class="text-4xl font-bold">Products</h1>
    <%= link_to 'New product', new_product_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="products" class="grid grid-cols-1 gap-5 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
    <% @products.each do |product| %>
      <%= render partial: 'product', locals: { product: product } %>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<div class="w-full mx-auto md:w-1/3">
  <h1 class="text-4xl font-bold">New product</h1>

  <%= render "products/form", product: @product %>

  <%= link_to 'Back to products', products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/products/show.html.erb
<div class="flex w-full mx-auto md:w-1/3">
  <div class="p-5 border border-gray-200 rounded-lg">

    <h2 class="mb-2 text-lg font-semibold"><%= @product.name %></h2>
    <div class="relative w-full mb-3 h-62 lg:mb-0">
        <img src="https://cdn.pixabay.com/photo/2017/01/11/11/33/cake-1971552__480.jpg" alt="Just a flower"
          class="object-fill w-full h-full rounded">
    </div>

    <p class="my-5">
      <strong class="block mb-1 font-medium">Description:</strong>
      <%= @product.description %>
    </p>

    <p class="my-5">
      <strong class="block mb-1 font-medium">Price:</strong>
      <%= @product.price %>
    </p>

    <p class="my-5">
      <strong class="block mb-1 font-medium">Balance:</strong>
      <%= @product.balance %>
    </p>

    <div class="flex justify-between">
      <%= link_to 'Add to Cart', add_to_cart_path(product_id: @product.id), method: :post, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"%>
      <%= link_to 'Edit', edit_product_path(@product), class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <%= button_to 'Destroy', product_path(@product), method: :delete, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <%= link_to 'Back', products_path, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    </div>
  </div>
</div>